apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prefect-worker-job-role
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch", "delete", "patch"]
  - apiGroups: [""]
    resources: ["pods", "pods/log", "pods/status"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prefect-worker-job-binding
subjects:
  - kind: ServiceAccount
    name: prefect-worker
    namespace: prefect
roleRef:
  kind: ClusterRole
  name: prefect-worker-job-role
  apiGroup: rbac.authorization.k8s.io
